server:
  port: 8080
spring:
  interface-clients:
    http:
      client-groups:
        verificationClient:
          base-url: http://localhost:8081
          read-timeout: 555s
      connect-timeout: 999s
  cloud:
#    loadbalancer:
#      clients:
#        verificationClient:
#          hint-header-name: "test"
    compatibility-verifier:
      enabled: false
    discovery:
      client:
        simple:
          instances:
            http-verification:
              - uri: http://localhost:8081
  application:
    name: http-verification-client
  http:
    client:
      read-timeout: 2222s
#http:
#  verification:
#    uri: http://localhost:8081